language: c

sudo: false

env:
  matrix:
    - CONDA_PY=2.7
    - CONDA_PY=3.3
    - CONDA_PY=3.4

  global:
    # BINSTAR_TOKEN
    - secure: "T7qEO3BVXdEP3J4bqE8X882KrdGD4L0cwbAjX/SZMm8e8bG/qmv7XWkxIDp/HakR5GlGr3EBGQDJi5g2CbmFwHjxXMbZ4Y0a3dvoCvfdBNUpBZcjPSil2X976aEkTR1MAL8X7VjuY4lwogqO2WU7Kzm1QaFWjWEl1fV/zxHYN9w="

install:
  - source devtools/travis-ci/install.sh
  - export PYTHONUNBUFFERED=true

script:
  # Build the conda package, running tests as part of the build.
  - conda build devtools/conda-recipe

after_script:
  # Run pyflakes.
  - pyflakes pdbfixer/*.py

after_success:
  - echo "after_success"
  - bash devtools/travis-ci/after_success.sh

